"
" WARNING! Do not edit this file!
"

if !has("python3")
    finish
endif

if exists("g:___SNAKE_CASE_PLACEHOLDER___plugin_loaded") && !exists("g:___SNAKE_CASE_PLACEHOLDER___developer_mode")
    finish
endif

let s:___SNAKE_CASE_PLACEHOLDER___pivvy_plugin_dir=expand("<sfile>:p:h")
let s:___SNAKE_CASE_PLACEHOLDER___pivvy_bootstrap_path= s:___SNAKE_CASE_PLACEHOLDER___pivvy_plugin_dir . "/bootstrap.py"

function! s:__SNAKE_CASE_PLACEHOLDER___pivvy_run_callb(i, ...)
    python3 pivvy._run_callb(int(vim.eval("a:i")), vim.eval("a:000"))
endfunction

" Hand over control to the python script
exe "py3file" . s:___SNAKE_CASE_PLACEHOLDER___pivvy_bootstrap_path

let g:___SNAKE_CASE_PLACEHOLDER___plugin_loaded=1
